// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTC-UaxJawK_PlArbSgX6vcXEkCuMUDsk',
    appId: '1:699920154828:web:b0841baec0f69e1fc28269',
    messagingSenderId: '699920154828',
    projectId: 'felcon-fitness',
    authDomain: 'felcon-fitness.firebaseapp.com',
    storageBucket: 'felcon-fitness.appspot.com',
    measurementId: 'G-YD1D19FZQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQQneelCQN3JIV2QWhZ30Q3LeknbUVX0E',
    appId: '1:699920154828:android:148a955c86cdd761c28269',
    messagingSenderId: '699920154828',
    projectId: 'felcon-fitness',
    storageBucket: 'felcon-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCluGwc9d_fkxszz4OGaUuXTOQVU5nZtig',
    appId: '1:699920154828:ios:eae1adf8fca40d9ec28269',
    messagingSenderId: '699920154828',
    projectId: 'felcon-fitness',
    storageBucket: 'felcon-fitness.appspot.com',
    iosBundleId: 'com.example.falconFittness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCluGwc9d_fkxszz4OGaUuXTOQVU5nZtig',
    appId: '1:699920154828:ios:eae1adf8fca40d9ec28269',
    messagingSenderId: '699920154828',
    projectId: 'felcon-fitness',
    storageBucket: 'felcon-fitness.appspot.com',
    iosBundleId: 'com.example.falconFittness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTC-UaxJawK_PlArbSgX6vcXEkCuMUDsk',
    appId: '1:699920154828:web:5390e12ba0f22ce0c28269',
    messagingSenderId: '699920154828',
    projectId: 'felcon-fitness',
    authDomain: 'felcon-fitness.firebaseapp.com',
    storageBucket: 'felcon-fitness.appspot.com',
    measurementId: 'G-39BQ04RKJ4',
  );
}
